server:
  port: 9090

spring:
  application:
    name: payment-query
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/query
    username: hello
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124

logging.level.net.open.payment: debug
logging.level.org.axonframework: debug
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info
