server:
  port: 9090

spring:
  application:
    name: payment-query
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/query
    username: barogo
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124