###
POST http://localhost:8080/deposit
Content-Type: application/json

{
  "holderId" : "3b1444f1-3890-4907-a859-c6a73bfe91e9",
  "accountId" : "962bbc13-04aa-4b19-ae88-70c821d0651f",
  "amount": 30
}

###