server:
  port: 8080

spring:
  application:
    name: transfer-command
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/command
    username: hello
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124

logging.level.net.open.payment: debug
logging.level.org.axonframework: debug